import { useEffect, useState } from 'react'
import boardGamesFallback from '../data/board-games.json'
import type { BoardGame } from '../types/board-game'

export type BoardGamesSource = 'loading' | 'live' | 'cached'

export type BoardGamesState = {
  games: BoardGame[]
  source: BoardGamesSource
}

// The checked-in fallback snapshot predates the categories/mechanics/condition/
// playtime-range/weight/thumbnail/notes fields and is only regenerated by
// running `npm run fetch:games` against Notion, so default them here rather
// than requiring every snapshot to be re-fetched.
const fallback: BoardGame[] = (boardGamesFallback as Partial<BoardGame>[]).map((game) => ({
  ...game,
  categories: game.categories ?? [],
  mechanics: game.mechanics ?? [],
  condition: game.condition ?? null,
  minPlaytime: game.minPlaytime ?? null,
  maxPlaytime: game.maxPlaytime ?? null,
  weight: game.weight ?? null,
  thumbnailUrl: game.thumbnailUrl ?? null,
  notes: game.notes ?? null,
  notes2: game.notes2 ?? null,
  notes3: game.notes3 ?? null,
})) as BoardGame[]

export function useBoardGames(): BoardGamesState {
  const [state, setState] = useState<BoardGamesState>({ games: fallback, source: 'loading' })

  useEffect(() => {
    let cancelled = false

    fetch('/api/games')
      .then((response) => {
        if (!response.ok) throw new Error(`Request failed: ${response.status}`)
        return response.json() as Promise<{ games: BoardGame[] }>
      })
      .then((data) => {
        if (!cancelled) setState({ games: data.games, source: 'live' })
      })
      .catch(() => {
        if (!cancelled) setState({ games: fallback, source: 'cached' })
      })

    return () => {
      cancelled = true
    }
  }, [])

  return state
}
