/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GamesRouteImport } from './routes/games'
import { Route as Minerals_fossilsRouteImport } from './routes/minerals_fossils'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SkylineDefenseRouteImport } from './routes/skyline-defense'
import { Route as StackRouteImport } from './routes/stack'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsPomodoroSimpleIndexRouteImport } from './routes/projects.pomodoro-simple.index'
import { Route as ProjectsPomodoroSimplePrivacyRouteImport } from './routes/projects.pomodoro-simple.privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const Minerals_fossilsRoute = Minerals_fossilsRouteImport.update({
  id: '/minerals_fossils',
  path: '/minerals_fossils',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkylineDefenseRoute = SkylineDefenseRouteImport.update({
  id: '/skyline-defense',
  path: '/skyline-defense',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPomodoroSimpleIndexRoute =
  ProjectsPomodoroSimpleIndexRouteImport.update({
    id: '/projects/pomodoro-simple/',
    path: '/projects/pomodoro-simple/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsPomodoroSimplePrivacyRoute =
  ProjectsPomodoroSimplePrivacyRouteImport.update({
    id: '/projects/pomodoro-simple/privacy',
    path: '/projects/pomodoro-simple/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/minerals_fossils': typeof Minerals_fossilsRoute
  '/music': typeof MusicRoute
  '/resume': typeof ResumeRoute
  '/skyline-defense': typeof SkylineDefenseRoute
  '/stack': typeof StackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/pomodoro-simple/privacy': typeof ProjectsPomodoroSimplePrivacyRoute
  '/projects/pomodoro-simple/': typeof ProjectsPomodoroSimpleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/minerals_fossils': typeof Minerals_fossilsRoute
  '/music': typeof MusicRoute
  '/resume': typeof ResumeRoute
  '/skyline-defense': typeof SkylineDefenseRoute
  '/stack': typeof StackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/pomodoro-simple/privacy': typeof ProjectsPomodoroSimplePrivacyRoute
  '/projects/pomodoro-simple': typeof ProjectsPomodoroSimpleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/minerals_fossils': typeof Minerals_fossilsRoute
  '/music': typeof MusicRoute
  '/resume': typeof ResumeRoute
  '/skyline-defense': typeof SkylineDefenseRoute
  '/stack': typeof StackRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/pomodoro-simple/privacy': typeof ProjectsPomodoroSimplePrivacyRoute
  '/projects/pomodoro-simple/': typeof ProjectsPomodoroSimpleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/games'
    | '/minerals_fossils'
    | '/music'
    | '/resume'
    | '/skyline-defense'
    | '/stack'
    | '/blog/$slug'
    | '/projects/'
    | '/projects/pomodoro-simple/privacy'
    | '/projects/pomodoro-simple/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/games'
    | '/minerals_fossils'
    | '/music'
    | '/resume'
    | '/skyline-defense'
    | '/stack'
    | '/blog/$slug'
    | '/projects'
    | '/projects/pomodoro-simple/privacy'
    | '/projects/pomodoro-simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/games'
    | '/minerals_fossils'
    | '/music'
    | '/resume'
    | '/skyline-defense'
    | '/stack'
    | '/blog_/$slug'
    | '/projects/'
    | '/projects/pomodoro-simple/privacy'
    | '/projects/pomodoro-simple/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRoute
  Minerals_fossilsRoute: typeof Minerals_fossilsRoute
  MusicRoute: typeof MusicRoute
  ResumeRoute: typeof ResumeRoute
  SkylineDefenseRoute: typeof SkylineDefenseRoute
  StackRoute: typeof StackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsPomodoroSimplePrivacyRoute: typeof ProjectsPomodoroSimplePrivacyRoute
  ProjectsPomodoroSimpleIndexRoute: typeof ProjectsPomodoroSimpleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minerals_fossils': {
      id: '/minerals_fossils'
      path: '/minerals_fossils'
      fullPath: '/minerals_fossils'
      preLoaderRoute: typeof Minerals_fossilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyline-defense': {
      id: '/skyline-defense'
      path: '/skyline-defense'
      fullPath: '/skyline-defense'
      preLoaderRoute: typeof SkylineDefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pomodoro-simple/': {
      id: '/projects/pomodoro-simple/'
      path: '/projects/pomodoro-simple'
      fullPath: '/projects/pomodoro-simple/'
      preLoaderRoute: typeof ProjectsPomodoroSimpleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pomodoro-simple/privacy': {
      id: '/projects/pomodoro-simple/privacy'
      path: '/projects/pomodoro-simple/privacy'
      fullPath: '/projects/pomodoro-simple/privacy'
      preLoaderRoute: typeof ProjectsPomodoroSimplePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRoute,
  Minerals_fossilsRoute: Minerals_fossilsRoute,
  MusicRoute: MusicRoute,
  ResumeRoute: ResumeRoute,
  SkylineDefenseRoute: SkylineDefenseRoute,
  StackRoute: StackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsPomodoroSimplePrivacyRoute: ProjectsPomodoroSimplePrivacyRoute,
  ProjectsPomodoroSimpleIndexRoute: ProjectsPomodoroSimpleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
